### ISSUE TITLE
npm 包未定义入口文件

### ISSUE THREAD

**Issue by CodingMonkeyzh** [jaywcjlove/iNotify#3]
通过 `npm install title-notify` 安装后（`"version": "1.0.9"`），`require("title-notify")` 时报错，提示找不到文件。
后来排查了下，发现 `package.json` 文件中并没有定义 `main` 入口，而且根目录下也没有定义 `index.js`。

**Comment by jaywcjlove** [comment]
@CodingMonkeyzh 有了 安装  `v1.0.10`
