### ISSUE TITLE
无法设置ICON 啊

### ISSUE THREAD

**Issue by HETAOGitHub** [jaywcjlove/iNotify#5]
`const notify = new INotify({

          // 标题

          message: '有消息了',

          // flash | scroll 闪烁还是滚动

          effect: 'flash',

          // 标题闪烁，或者滚动速度

          interval: 1000,

          notification: {

            title: `${revMsg.content.user.name}给你发送了新消息`,

            icon: revMsg.content.extra.avatar,

            body: revMsg.content.content,

          },

        });`

我确定内容是有的。 这个revMsg.content.extra.avatar 中的值是正确的。 是一个图片地址。http://static-avatar-user-cdn.kdjz.com/test/avatar/400408/2016/08/31/7f9f5dff37cf5f1cd3f4e7a581437b7f.jpg

但是弹出的通知窗口却是默认的favicon.ico  是不是只能用.ico 的图片啊？

**Comment by jaywcjlove** [comment]
ICON图片设置在HTML中

```html
<link rel="shortcut icon" type="image/png" href="/favicon.png"/>
<link rel="shortcut icon" type="image/png" href="http://eg.com/favicon.png"/>
```

**Comment by jaywcjlove** [comment]
`title-notify@1.0.12`

下载新版本，解决了此问题。

**Comment by HETAOGitHub** [comment]
很抱歉，仍然是不能设置。
![image](https://cloud.githubusercontent.com/assets/13549879/20027133/6605eca8-a346-11e6-81e4-f434053d2ebf.png)代码是这样的
![image](https://cloud.githubusercontent.com/assets/13549879/20027140/824614ba-a346-11e6-88e9-6d5a52f9e074.png)
其中的输出语句的输出结果是这样的。

但是通知的的icon 还是默认的 icon

麻烦您再看看 是什么情况？

**Comment by jaywcjlove** [comment]
<img width="702" alt="1" src="https://cloud.githubusercontent.com/assets/1680273/20027502/a8e29ab2-a350-11e6-8b81-ba4ccd346d3e.png">

希望你引用到了新版本js

![image](https://cloud.githubusercontent.com/assets/1680273/20027531/9564c766-a351-11e6-9f2e-4b9b6787eaee.png)

**Comment by HETAOGitHub** [comment]
重新npm 了你的包。  现在可以了。  看来是我没有更新到））
