### ISSUE TITLE
有关闭Icon数字的开关吗？

### ISSUE THREAD

**Issue by hymanwu** [jaywcjlove/iNotify#9]
你这个可以用在商业项目上吗:）

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/27848523-41af4732-6178-11e7-8eb1-51f0c6e1bec3.png)

MIT协议，的限制， @hymanwu

- Liability
- Warranty

## setFavicon

设置icon 显示数字

```js
iNotify.setFavicon(10)
```

## faviconClear

清除数字显示原来的icon

```js
iNotify.faviconClear()
```

**Comment by hymanwu** [comment]
噢，谢谢那我就用咯。
意思是一开始初始化就会有icon咯？我想初始化就不要改变icon这功能呢?

**Comment by jaywcjlove** [comment]
@hymanwu 看文档

**Comment by hymanwu** [comment]
TKS
